### PR TITLE
Adding offline capabilities now that simulator is 2.0

### PR DESCRIPTION
**Pull request by darkwing**
Now that the Simulator we're pushing is 2.0, we can add offline capabilities to our app without it bombing the simulator.

### CODE REVIEW

**Comment by fwenzel** [comment]
The change is legit (r+), though I haven't loaded it into the simulator to test.

**Comment by darkwing** [comment]
I'd love for someone to ... test ... things?? @csuwldcat ?

**Comment by csuwildcat** [comment]
Well I installed it and used it in the simulator, everything looked good, but what specifically was I supposed to be watching for?

**Comment by darkwing** [comment]
Just wanted you to have tried it ;)  If it's good, it's mergable.

**Comment by darkwing** [comment]
Retested, made a minor update, all set!

**Pull request merged**
